# 📦 Data Loading & Cleaning

In [1]:
import pandas as pd
import os

In [2]:
base = r'C:\Users\KRISH\OneDrive\Music\Desktop\retail and food services\retail-analysis'

df = pd.read_csv(base + r'\data\retail.csv')
print("✅ Data Loaded!")
print("Shape:", df.shape)
df.head()

✅ Data Loaded!
Shape: (15048, 4)

        month naics_code          kind_of_business     value
0  2024-04-01       4481           Clothing stores   18442.0
1  2024-01-01        445  Food and beverage stores   81781.0
2  2023-10-01       4451            Grocery stores   73546.0
3  2023-07-01    no code                   GAFO(1)  129723.0
4  2022-04-01    no code                   GAFO(1)  129036.0

In [3]:
print("Columns:", df.columns.tolist())
print("\nData Types:")
print(df.dtypes)
print("\nMissing Values:")
print(df.isnull().sum())

Columns: ['month', 'naics_code', 'kind_of_business', 'value']

Data Types:
month                object
naics_code           object
kind_of_business     object
value               float64
dtype: object

Missing Values:
month                0
naics_code           0
kind_of_business     0
value               92
dtype: int64

In [4]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df['month'] = pd.to_datetime(df['month'])
df['naics_code'] = pd.to_numeric(df['naics_code'], errors='coerce')
df['value'] = pd.to_numeric(df['value'], errors='coerce')
df.dropna(inplace=True)

print("✅ Data Cleaned!")
print("Shape:", df.shape)
df.head()

✅ Data Cleaned!
Shape: (11392, 4)

       month  naics_code          kind_of_business    value
0 2024-04-01      4481.0           Clothing stores  18442.0
1 2024-01-01       445.0  Food and beverage stores  81781.0
2 2023-10-01      4451.0            Grocery stores  73546.0
5 2023-08-01      4451.0            Grocery stores  73390.0
7 2020-10-01     44831.0            Jewelry stores   3010.0

In [5]:
df.to_csv(base + r'\data\retail_clean.csv', index=False)
print("✅ Saved → retail_clean.csv!")

✅ Saved → retail_clean.csv!