# 📊 Exploratory Data Analysis (EDA)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

base = r'C:\Users\KRISH\OneDrive\Music\Desktop\retail and food services\retail-analysis'
df = pd.read_csv(base + r'\data\retail_clean.csv', parse_dates=['month'])
df['year'] = df['month'].dt.year

print("✅ Data Loaded!")
print("Shape:", df.shape)

✅ Data Loaded!
Shape: (11392, 5)

In [2]:
df.describe()

,month,naics_code,value,year
count,11392,11392.000000,11392.000000,11392.000000
mean,2008-05-04 02:26:07.415730432,12203.732795,20970.312763,2007.882549
min,1992-01-01 00:00:00,441.000000,86.000000,1992.000000
25%,2000-03-01 00:00:00,448.000000,5159.000000,2000.000000
50%,2008-05-01 00:00:00,4441.000000,12449.000000,2008.000000
75%,2016-07-01 00:00:00,4541.000000,29945.250000,2016.000000
max,2024-12-01 00:00:00,45431.000000,143325.000000,2024.000000
std,NaN,18283.433533,22353.144865,9.469656

In [3]:
top10 = df.groupby('kind_of_business')['value'].sum().nlargest(10)
print(top10)

kind_of_business
Motor vehicle and parts dealers              30757252.0
Food and beverage stores                     19679692.0
General merchandise stores                   18410342.0
Grocery stores                               17698661.0
Food services and drinking places            16578704.0
Nonstore retailers                           14582407.0
Gasoline stations                            13023431.0
Other general merchandise stores             12347515.0
Electronic shopping and mail order houses    12041310.0
Warehouse clubs and superstores              10541605.0
Name: value, dtype: float64

In [4]:
yearly = df.groupby('year')['value'].sum()
print(yearly)

year
1992     3123669.0
1993     3326385.0
1994     3571077.0
1995     3747194.0
1996     3956177.0
1997     4156691.0
1998     4362286.0
1999     4718016.0
2000     5025128.0
2001     5210023.0
2002     5373782.0
2003     5633701.0
2004     5991383.0
2005     6405671.0
2006     6764657.0
2007     7011047.0
2008     7008396.0
2009     6641948.0
2010     6945009.0
2011     7403649.0
2012     7735703.0
2013     8009669.0
2014     8347768.0
2015     8584583.0
2016     8816874.0
2017     9209939.0
2018     9613233.0
2019     9934753.0
2020    10299449.0
2021    11871461.0
2022    12897051.0
2023    13396076.0
2024    13801355.0
Name: value, dtype: float64

In [5]:
df.corr(numeric_only=True)

            naics_code     value      year
naics_code    1.000000 -0.331104 -0.022128
value        -0.331104  1.000000  0.378392
year         -0.022128  0.378392  1.000000